from selenium import webdriver
from selenium.webdriver.support.select import Select
import sys, time, unittest
import common.ReadConfig as co
sys.path.append('..')
from pages.loginpage import LoginPage
from pages.jqxxpage import JqxxPage
import utils.util as ut
file1 = ut.DATA_PATH+'/user_data.csv'
data1 = ut.get_data(file1)
file2 = ut.DATA_PATH+'/jqxx_data.csv'
data2 = ut.get_data(file2)
url = co.getbrowsername('Url')
mark1 = 1

class TestJqxx(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.driver = webdriver.Firefox()
        cls.driver.maximize_window()
        cls.driver.get(url)
        time.sleep(2)
        cls.dl = LoginPage(cls.driver, Select)
        cls.jqxx = JqxxPage(cls.driver, Select)

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def tearDown(self):
        global mark1
        mark1 += 1
        self.driver.refresh()



    def testcase1(self):
        '''用例1、新增一级A监区成功'''
        self.dl.input_name(data1[mark1][0])
        time.sleep(2)
        self.dl.input_pwd(data1[mark1][1])
        time.sleep(2)
        self.dl.click_login()
        time.sleep(3)
        self.jqxx.click_jcxxgl()
        time.sleep(3)
        self.jqxx.click_jqxxgl()
        time.sleep(3)
        self.jqxx.switch_jqtj()
        time.sleep(3)
        self.jqxx.click_jqtj()
        time.sleep(3)
        self.jqxx.click_zflx()
        time.sleep(3)
        self.jqxx.click_zflxqx()
        time.sleep(3)
        self.jqxx.click_zflx()
        time.sleep(3)
        self.jqxx.input_jqmc(data2[mark1][2])
        time.sleep(3)
        self.jqxx.input_jqbh(data2[mark1][3])
        time.sleep(3)
        self.jqxx.click_xsrq()
        time.sleep(3)
        self.jqxx.click_ygrq()
        time.sleep(3)
        self.jqxx.click_ygrqxz()
        time.sleep(3)
        self.jqxx.input_ksrq(data2[mark1][4])
        time.sleep(3)
        self.jqxx.input_jzrq(data2[mark1][5])
        time.sleep(3)
        self.jqxx.click_xssj()
        time.sleep(3)
        self.jqxx.click_ygsj()
        time.sleep(3)
        self.jqxx.click_ygsjxz()
        time.sleep(3)
        self.jqxx.input_kssj(data2[mark1][6])
        time.sleep(3)
        self.jqxx.input_jzsj(data2[mark1][7])
        time.sleep(3)
        self.jqxx.click_bcnr()

    def testcase2(self):
        '''用例2、新增二级A-1监区成功'''
        self.jqxx.click_jcxxgl()
        time.sleep(3)
        self.jqxx.click_jqxxgl()
        time.sleep(3)
        self.jqxx.switch_jqtj()
        time.sleep(3)
        self.jqxx.click_jqtj()
        time.sleep(3)
        self.jqxx.click_sjjq()
        time.sleep(3)
        self.jqxx.input_sjjq(data2[mark1][1])
        time.sleep(3)
        self.jqxx.click_zflx()
        time.sleep(3)
        self.jqxx.click_zflxqx()
        time.sleep(3)
        self.jqxx.click_zflx()
        time.sleep(3)
        self.jqxx.input_jqmc(data2[mark1][2])
        time.sleep(3)
        self.jqxx.input_jqbh(data2[mark1][3])
        time.sleep(3)
        self.jqxx.click_xsrq()
        time.sleep(3)
        self.jqxx.click_ygrq()
        time.sleep(3)
        self.jqxx.click_ygrqxz()
        time.sleep(3)
        self.jqxx.input_ksrq(data2[mark1][4])
        time.sleep(3)
        self.jqxx.input_jzrq(data2[mark1][5])
        time.sleep(3)
        self.jqxx.click_xssj()
        time.sleep(3)
        self.jqxx.click_ygsj()
        time.sleep(3)
        self.jqxx.click_ygsjxz()
        time.sleep(3)
        self.jqxx.input_kssj(data2[mark1][6])
        time.sleep(3)
        self.jqxx.input_jzsj(data2[mark1][7])
        time.sleep(3)
        self.jqxx.click_bcnr()

    def testcase3(self):
        '''用例3、新增一级B监区成功'''
        self.jqxx.click_jcxxgl()
        time.sleep(3)
        self.jqxx.click_jqxxgl()
        time.sleep(3)
        self.jqxx.switch_jqtj()
        time.sleep(3)
        self.jqxx.click_jqtj()
        time.sleep(3)
        self.jqxx.click_zflx()
        time.sleep(3)
        self.jqxx.click_zflxqx()
        time.sleep(3)
        self.jqxx.click_zflx()
        time.sleep(3)
        self.jqxx.input_jqmc(data2[mark1][2])
        time.sleep(3)
        self.jqxx.input_jqbh(data2[mark1][3])
        time.sleep(3)
        self.jqxx.click_xsrq()
        time.sleep(3)
        self.jqxx.click_ygrq()
        time.sleep(3)
        self.jqxx.click_ygrqxz()
        time.sleep(3)
        self.jqxx.input_ksrq(data2[mark1][4])
        time.sleep(3)
        self.jqxx.input_jzrq(data2[mark1][5])
        time.sleep(3)
        self.jqxx.click_xssj()
        time.sleep(3)
        self.jqxx.click_ygsj()
        time.sleep(3)
        self.jqxx.click_ygsjxz()
        time.sleep(3)
        self.jqxx.input_kssj(data2[mark1][6])
        time.sleep(3)
        self.jqxx.input_jzsj(data2[mark1][7])
        time.sleep(3)
        self.jqxx.click_bcnr()


    def testcase4(self):
        '''用例4、新增二级B-1监区成功'''
        self.jqxx.click_jcxxgl()
        time.sleep(3)
        self.jqxx.click_jqxxgl()
        time.sleep(3)
        self.jqxx.switch_jqtj()
        time.sleep(3)
        self.jqxx.click_jqtj()
        time.sleep(3)
        self.jqxx.click_sjjq()
        time.sleep(3)
        self.jqxx.input_sjjq(data2[mark1][1])
        time.sleep(3)
        self.jqxx.click_zflx()
        time.sleep(3)
        self.jqxx.click_zflxqx()
        time.sleep(3)
        self.jqxx.click_zflx()
        time.sleep(3)
        self.jqxx.input_jqmc(data2[mark1][2])
        time.sleep(3)
        self.jqxx.input_jqbh(data2[mark1][3])
        time.sleep(3)
        self.jqxx.click_xsrq()
        time.sleep(3)
        self.jqxx.click_ygrq()
        time.sleep(3)
        self.jqxx.click_ygrqxz()
        time.sleep(3)
        self.jqxx.input_ksrq(data2[mark1][4])
        time.sleep(3)
        self.jqxx.input_jzrq(data2[mark1][5])
        time.sleep(3)
        self.jqxx.click_xssj()
        time.sleep(3)
        self.jqxx.click_ygsj()
        time.sleep(3)
        self.jqxx.click_ygsjxz()
        time.sleep(3)
        self.jqxx.input_kssj(data2[mark1][6])
        time.sleep(3)
        self.jqxx.input_jzsj(data2[mark1][7])
        time.sleep(3)
        self.jqxx.click_bcnr()

if __name__=='__main__':
    unittest.main()