from selenium import webdriver
from selenium.webdriver.support.select import Select
import sys,time,unittest
import common.ReadConfig as co
sys.path.append('..')
from pages.loginpage import LoginPage
from pages.zjlxpage import ZjlxPage
import utils.util as ut
file1 = ut.DATA_PATH+'/user_data.csv'
data1 = ut.get_data(file1)
file2 = ut.DATA_PATH+'/zjlx_data.csv'
data2 = ut.get_data(file2)
url = co.getbrowsername('Url')
mark1 = 1
mark2 = 1
sxzlx1 = '1' #上
sxzlx2 = '2' #下
sfgk11 = '0'
sfjrxftj11 = '2'
sfkycz11 = '0'

class TestZjlx(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.driver = webdriver.Firefox()
        cls.driver.maximize_window()
        cls.driver.get(url)
        time.sleep(2)
        cls.dl = LoginPage(cls.driver, Select)
        cls.zj = ZjlxPage(cls.driver, Select)

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def tearDown(self):
        global mark1
        mark1 += 1
        self.driver.refresh()

    def testcase1(self):
        '''用例1，新增-整体下账成功'''
        self.dl.input_name(data1[mark1][0])
        time.sleep(2)
        self.dl.input_pwd(data1[mark1][1])
        time.sleep(3)
        self.dl.click_login()
        time.sleep(3)
        self.zj.click_zjywgl()
        time.sleep(3)
        self.zj.click_zjlx()
        time.sleep(3)
        self.zj.switch_zjlxtj()
        time.sleep(3)
        self.zj.click_zjlxtj()
        time.sleep(3)
        self.zj.click_sjzjlx()
        time.sleep(3)
        self.zj.input_sjzjlxmc(data2[mark1][1])
        time.sleep(3)
        self.zj.input_zjlxmc(data2[mark1][2])
        time.sleep(3)
        self.zj.input_zjlxbh(data2[mark1][3])
        time.sleep(3)
        self.zj.select_sxzlx(sxzlx2)
        time.sleep(3)
        #self.zj.select_sfgk(sfgk11)
        #time.sleep(3)
        #self.zj.select_sfjrxftj(sfjrxftj11)
        #time.sleep(3)
        #self.zj.select_sfkycz(sfkycz11)
        #time.sleep(3)
        self.zj.input_A(data2[mark1][4])
        time.sleep(3)
        self.zj.input_B(data2[mark1][5])
        time.sleep(3)
        self.zj.input_C(data2[mark1][6])
        time.sleep(3)
        self.zj.click_bcnr()

    def testcase2(self):
        '''用例2，新增-整体上账成功'''
        self.zj.click_zjywgl()
        time.sleep(3)
        self.zj.click_zjlx()
        time.sleep(3)
        self.zj.switch_zjlxtj()
        time.sleep(3)
        self.zj.click_zjlxtj()
        time.sleep(3)
        self.zj.click_sjzjlx()
        time.sleep(3)
        self.zj.input_sjzjlxmc(data2[mark1][1])
        time.sleep(3)
        self.zj.input_zjlxmc(data2[mark1][2])
        time.sleep(3)
        self.zj.input_zjlxbh(data2[mark1][3])
        time.sleep(3)
        self.zj.select_sxzlx(sxzlx1)
        time.sleep(3)
        self.zj.input_A(data2[mark1][4])
        time.sleep(3)
        self.zj.input_B(data2[mark1][5])
        time.sleep(3)
        self.zj.input_C(data2[mark1][6])
        time.sleep(3)
        self.zj.click_bcnr()

    def testcase3(self):
        '''用例3，新增-B下账资金类型00102成功'''
        self.zj.click_zjywgl()
        time.sleep(3)
        self.zj.click_zjlx()
        time.sleep(3)
        self.zj.switch_zjlxtj()
        time.sleep(3)
        self.zj.click_zjlxtj()
        time.sleep(3)
        self.zj.click_sjzjlx()
        time.sleep(3)
        self.zj.input_sjzjlxmc(data2[mark1][1])
        time.sleep(3)
        self.zj.input_zjlxmc(data2[mark1][2])
        time.sleep(3)
        self.zj.input_zjlxbh(data2[mark1][3])
        time.sleep(3)
        self.zj.select_sxzlx(sxzlx2)
        time.sleep(3)
        self.zj.input_A(data2[mark1][4])
        time.sleep(3)
        self.zj.input_B(data2[mark1][5])
        time.sleep(3)
        self.zj.input_C(data2[mark1][6])
        time.sleep(3)
        self.zj.click_bcnr()

    def testcase4(self):
        '''用例4，新增-B下账资金类型00102成功'''
        self.zj.click_zjywgl()
        time.sleep(3)
        self.zj.click_zjlx()
        time.sleep(3)
        self.zj.switch_zjlxtj()
        time.sleep(3)
        self.zj.click_zjlxtj()
        time.sleep(3)
        self.zj.click_sjzjlx()
        time.sleep(3)
        self.zj.input_sjzjlxmc(data2[mark1][1])
        time.sleep(3)
        self.zj.input_zjlxmc(data2[mark1][2])
        time.sleep(3)
        self.zj.input_zjlxbh(data2[mark1][3])
        time.sleep(3)
        self.zj.select_sxzlx(sxzlx2)
        time.sleep(3)
        self.zj.input_A(data2[mark1][4])
        time.sleep(3)
        self.zj.input_B(data2[mark1][5])
        time.sleep(3)
        self.zj.input_C(data2[mark1][6])
        time.sleep(3)
        self.zj.click_bcnr()

    def testcase5(self):
        '''用例5，新增-C下账资金类型00103成功'''
        self.zj.click_zjywgl()
        time.sleep(3)
        self.zj.click_zjlx()
        time.sleep(3)
        self.zj.switch_zjlxtj()
        time.sleep(3)
        self.zj.click_zjlxtj()
        time.sleep(3)
        self.zj.click_sjzjlx()
        time.sleep(3)
        self.zj.input_sjzjlxmc(data2[mark1][1])
        time.sleep(3)
        self.zj.input_zjlxmc(data2[mark1][2])
        time.sleep(3)
        self.zj.input_zjlxbh(data2[mark1][3])
        time.sleep(3)
        self.zj.select_sxzlx(sxzlx2)
        time.sleep(3)
        self.zj.input_A(data2[mark1][4])
        time.sleep(3)
        self.zj.input_B(data2[mark1][5])
        time.sleep(3)
        self.zj.input_C(data2[mark1][6])
        time.sleep(3)
        self.zj.click_bcnr()

    def testcase6(self):
        '''用例6，新增-A上账资金类型00201成功'''
        self.zj.click_zjywgl()
        time.sleep(3)
        self.zj.click_zjlx()
        time.sleep(3)
        self.zj.switch_zjlxtj()
        time.sleep(3)
        self.zj.click_zjlxtj()
        time.sleep(3)
        self.zj.click_sjzjlx()
        time.sleep(3)
        self.zj.input_sjzjlxmc(data2[mark1][1])
        time.sleep(3)
        self.zj.input_zjlxmc(data2[mark1][2])
        time.sleep(3)
        self.zj.input_zjlxbh(data2[mark1][3])
        time.sleep(3)
        self.zj.select_sxzlx(sxzlx2)
        time.sleep(3)
        self.zj.input_A(data2[mark1][4])
        time.sleep(3)
        self.zj.input_B(data2[mark1][5])
        time.sleep(3)
        self.zj.input_C(data2[mark1][6])
        time.sleep(3)
        self.zj.click_bcnr()

    def testcase7(self):
        '''用例7，新增-B上账资金类型00202成功'''
        self.zj.click_zjywgl()
        time.sleep(3)
        self.zj.click_zjlx()
        time.sleep(3)
        self.zj.switch_zjlxtj()
        time.sleep(3)
        self.zj.click_zjlxtj()
        time.sleep(3)
        self.zj.click_sjzjlx()
        time.sleep(3)
        self.zj.input_sjzjlxmc(data2[mark1][1])
        time.sleep(3)
        self.zj.input_zjlxmc(data2[mark1][2])
        time.sleep(3)
        self.zj.input_zjlxbh(data2[mark1][3])
        time.sleep(3)
        self.zj.select_sxzlx(sxzlx2)
        time.sleep(3)
        self.zj.input_A(data2[mark1][4])
        time.sleep(3)
        self.zj.input_B(data2[mark1][5])
        time.sleep(3)
        self.zj.input_C(data2[mark1][6])
        time.sleep(3)
        self.zj.click_bcnr()

    def testcase8(self):
        '''用例8，新增-C上账资金类型00203成功'''
        self.zj.click_zjywgl()
        time.sleep(3)
        self.zj.click_zjlx()
        time.sleep(3)
        self.zj.switch_zjlxtj()
        time.sleep(3)
        self.zj.click_zjlxtj()
        time.sleep(3)
        self.zj.click_sjzjlx()
        time.sleep(3)
        self.zj.input_sjzjlxmc(data2[mark1][1])
        time.sleep(3)
        self.zj.input_zjlxmc(data2[mark1][2])
        time.sleep(3)
        self.zj.input_zjlxbh(data2[mark1][3])
        time.sleep(3)
        self.zj.select_sxzlx(sxzlx2)
        time.sleep(3)
        self.zj.input_A(data2[mark1][4])
        time.sleep(3)
        self.zj.input_B(data2[mark1][5])
        time.sleep(3)
        self.zj.input_C(data2[mark1][6])
        time.sleep(3)
        self.zj.click_bcnr()


if __name__=='__main__':
    unittest.main()