from selenium import webdriver
from selenium.webdriver.support.select import Select
import sys,time,unittest,re
import common.ReadConfig as co
sys.path.append('..')
from pages.loginpage import LoginPage
from pages.zf_userpage import UserPagezf
from pages.jqxxpage import JqxxPage
from pages.xfgk1cyed1xfedpage import Cyed1xfedPage
import utils.util as ut
file1 = ut.DATA_PATH+'/user_data.csv'
data1 = ut.get_data(file1)
file2 = ut.DATA_PATH+'/zfzjq_data.csv'
data2 = ut.get_data(file2)
url = co.getbrowsername('Url')
mark1 = 1

class TestCyed(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.driver = webdriver.Firefox()
        cls.driver.maximize_window()
        cls.driver.get(url)
        time.sleep(3)
        cls.dl = LoginPage(cls.driver, Select)
        cls.zfuser = UserPagezf(cls.driver, Select)
        cls.jqxx = JqxxPage(cls.driver, Select)
        cls.cyed1 = Cyed1xfedPage(cls.driver, Select)

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()

    def tearDown(self):
        global mark1
        mark1 += 1
        self.driver.refresh()

    def testcase01(self):
        '''用例1，高额等级-》低额等级，【未超额】历史有计入管控消费=》转级后新管控>历史记录管控，新可用=新管控-历史记录管控【可购物】'''
        self.dl.input_name(data1[mark1][0])
        time.sleep(3)
        self.dl.input_pwd(data1[mark1][1])
        time.sleep(3)
        self.dl.click_login()
        time.sleep(3)

        #1、修改处遇等级额度【高】【低】
        self.cyed1.click_zfxfgk()
        time.sleep(2)
        self.cyed1.click_cyed()
        time.sleep(2)
        self.cyed1.switch_cyed()
        time.sleep(2)
        self.cyed1.click_ze1bxz()
        time.sleep(2)
        self.cyed1.click_a1bxz()
        time.sleep(2)
        self.cyed1.click_b1bxz()
        time.sleep(2)
        self.cyed1.click_gwcsbxz()
        time.sleep(2)

        # ------【一级处遇等级{高}】A
        self.cyed1.click_a1xz()
        time.sleep(2)
        self.cyed1.input_a1(data2[mark1][6])
        time.sleep(2)
        # ------【二级处遇等级{高}】A
        self.cyed1.click_a2xz()
        time.sleep(2)
        self.cyed1.input_a2(data2[mark1][8])
        time.sleep(2)

        self.cyed1.click_cyedbc()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #2、创建罪犯关联【高】处遇
        self.cyed1.click_jcxxgl()
        time.sleep(2)
        self.cyed1.click_zfxxgl()
        time.sleep(2)
        self.cyed1.switch_zftj()
        time.sleep(2)
        self.cyed1.click_zftj()
        time.sleep(2)
        self.cyed1.click_ssjq()
        time.sleep(2)
        self.cyed1.input_ssjq(data2[mark1][19])
        time.sleep(2)
        self.cyed1.input_zfxm(data2[mark1][1])
        time.sleep(2)
        self.cyed1.input_zfbh(data2[mark1][2])
        time.sleep(2)
        self.cyed1.click_zfxb()
        time.sleep(2)
        self.cyed1.input_zfxbsr(data2[mark1][3])
        time.sleep(2)
        self.cyed1.click_cydj()
        time.sleep(2)
        self.cyed1.input_cydj(data2[mark1][5])
        time.sleep(2)
        self.cyed1.click_srlb()
        time.sleep(2)
        self.cyed1.input_srlb(data2[mark1][4])
        time.sleep(2)
        self.cyed1.click_zflx()
        time.sleep(2)
        self.cyed1.click_bcnr()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #3、罪犯资金上账A
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_xzsz()
        time.sleep(2)
        self.cyed1.switch_outframe()
        time.sleep(2)
        self.cyed1.click_zjszgb()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_szzjfl()
        time.sleep(2)
        self.cyed1.input_szzjfl(data2[mark1][9])
        time.sleep(2)
        self.cyed1.click_szzjlx()
        time.sleep(2)
        self.cyed1.input_szzjlx(data2[mark1][10])
        time.sleep(2)
        self.cyed1.input_szzfxm(data2[mark1][2])
        time.sleep(2)
        self.cyed1.input_szje(data2[mark1][11])
        time.sleep(2)
        self.cyed1.click_qbsz()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szgb()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_tjsz()
        time.sleep(2)
        self.cyed1.click_qrsz()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #4、修改商品在售价格A
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 一关
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_zsspgl()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(4)
        self.cyed1.click_spyjtj()
        time.sleep(3)
        self.cyed1.switch_outframe()
        time.sleep(3)
        self.cyed1.click_zsspgb()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(3)
        self.cyed1.click_xzsp()
        time.sleep(3)
        # 商品1
        self.cyed1.input_spbhsrk(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)
        # 商品2
        self.cyed1.input_spbhsrk(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)

        self.cyed1.click_gbspxz()
        time.sleep(3)
        # 商品一新临售
        self.cyed1.input_sp1xls(data2[mark1][14])
        time.sleep(3)
        # 商品二新临售
        self.cyed1.input_sp2xls(data2[mark1][17])
        time.sleep(3)
        self.cyed1.click_tjtj()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 二开
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #5、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #6、罪犯转处遇等级【低】
        self.zfuser.click_jcxxgl()
        time.sleep(3)
        self.zfuser.click_zfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.input_zfxxcxbhsrk(data2[mark1][2])
        time.sleep(3)
        self.zfuser.click_zfxxglcxan()
        time.sleep(3)
        self.zfuser.click_zfxxglgx()
        time.sleep(3)
        self.zfuser.plzcydj()
        time.sleep(2)
        self.zfuser.switch_outframe()
        time.sleep(3)
        self.zfuser.click_gbzfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.select_xzcydj('128') #低处遇等级
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.driver.refresh()

        #7、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        self.cyed1.switch_outframe()
        self.b = self.zfuser.gett_ddcjsbtknr()
        try:
            self.assertIn('订单创建失败', self.b)
        except:
            self.cyed1.get_img(ut.IMG_PATH + '/罪犯转处遇等级模块_%d.png' % (mark1))
            raise Exception

    def testcase02(self):
        '''用例2，高额等级-》低额等级，【超额】历史有计入管控消费=》转级后新管控=历史记录管控，新可用=0【不可购物】'''
        self.dl.input_name(data1[mark1][0])
        time.sleep(3)
        self.dl.input_pwd(data1[mark1][1])
        time.sleep(3)
        self.dl.click_login()
        time.sleep(3)

        #1、修改处遇等级额度【高】【低】
        self.cyed1.click_zfxfgk()
        time.sleep(2)
        self.cyed1.click_cyed()
        time.sleep(2)
        self.cyed1.switch_cyed()
        time.sleep(2)
        self.cyed1.click_ze1bxz()
        time.sleep(2)
        self.cyed1.click_a1bxz()
        time.sleep(2)
        self.cyed1.click_b1bxz()
        time.sleep(2)
        self.cyed1.click_gwcsbxz()
        time.sleep(2)

        # ------【一级处遇等级{高}】A
        self.cyed1.click_a1xz()
        time.sleep(2)
        self.cyed1.input_a1(data2[mark1][6])
        time.sleep(2)
        # ------【二级处遇等级{高}】A
        self.cyed1.click_a2xz()
        time.sleep(2)
        self.cyed1.input_a2(data2[mark1][8])
        time.sleep(2)

        self.cyed1.click_cyedbc()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #2、创建罪犯关联【高】处遇
        self.cyed1.click_jcxxgl()
        time.sleep(2)
        self.cyed1.click_zfxxgl()
        time.sleep(2)
        self.cyed1.switch_zftj()
        time.sleep(2)
        self.cyed1.click_zftj()
        time.sleep(2)
        self.cyed1.click_ssjq()
        time.sleep(2)
        self.cyed1.input_ssjq(data2[mark1][19])
        time.sleep(2)
        self.cyed1.input_zfxm(data2[mark1][1])
        time.sleep(2)
        self.cyed1.input_zfbh(data2[mark1][2])
        time.sleep(2)
        self.cyed1.click_zfxb()
        time.sleep(2)
        self.cyed1.input_zfxbsr(data2[mark1][3])
        time.sleep(2)
        self.cyed1.click_cydj()
        time.sleep(2)
        self.cyed1.input_cydj(data2[mark1][5])
        time.sleep(2)
        self.cyed1.click_srlb()
        time.sleep(2)
        self.cyed1.input_srlb(data2[mark1][4])
        time.sleep(2)
        self.cyed1.click_zflx()
        time.sleep(2)
        self.cyed1.click_bcnr()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #3、罪犯资金上账A
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_xzsz()
        time.sleep(2)
        self.cyed1.switch_outframe()
        time.sleep(2)
        self.cyed1.click_zjszgb()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_szzjfl()
        time.sleep(2)
        self.cyed1.input_szzjfl(data2[mark1][9])
        time.sleep(2)
        self.cyed1.click_szzjlx()
        time.sleep(2)
        self.cyed1.input_szzjlx(data2[mark1][10])
        time.sleep(2)
        self.cyed1.input_szzfxm(data2[mark1][2])
        time.sleep(2)
        self.cyed1.input_szje(data2[mark1][11])
        time.sleep(2)
        self.cyed1.click_qbsz()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szgb()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_tjsz()
        time.sleep(2)
        self.cyed1.click_qrsz()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #4、修改商品在售价格A
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 一关
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_zsspgl()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(4)
        self.cyed1.click_spyjtj()
        time.sleep(3)
        self.cyed1.switch_outframe()
        time.sleep(3)
        self.cyed1.click_zsspgb()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(3)
        self.cyed1.click_xzsp()
        time.sleep(3)
        # 商品1
        self.cyed1.input_spbhsrk(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)
        # 商品2
        self.cyed1.input_spbhsrk(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)

        self.cyed1.click_gbspxz()
        time.sleep(3)
        # 商品一新临售
        self.cyed1.input_sp1xls(data2[mark1][14])
        time.sleep(3)
        # 商品二新临售
        self.cyed1.input_sp2xls(data2[mark1][17])
        time.sleep(3)
        self.cyed1.click_tjtj()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 二开
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #5、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #6、罪犯转处遇等级【低】
        self.zfuser.click_jcxxgl()
        time.sleep(3)
        self.zfuser.click_zfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.input_zfxxcxbhsrk(data2[mark1][2])
        time.sleep(3)
        self.zfuser.click_zfxxglcxan()
        time.sleep(3)
        self.zfuser.click_zfxxglgx()
        time.sleep(3)
        self.zfuser.plzcydj()
        time.sleep(2)
        self.zfuser.switch_outframe()
        time.sleep(3)
        self.zfuser.click_gbzfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.select_xzcydj('128') #低处遇等级
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.driver.refresh()

        #7、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        self.cyed1.switch_outframe()
        self.b = self.zfuser.gett_ddcjsbtknr()
        try:
            self.assertIn('订单创建失败', self.b)
        except:
            self.cyed1.get_img(ut.IMG_PATH + '/罪犯转处遇等级模块_%d.png' % (mark1))
            raise Exception

    def testcase03(self):
        '''用例3，高额等级-》低额等级，【超额】历史有计入管控消费=》转级后新管控<历史记录管控，新可用=0【不可购物】'''
        self.dl.input_name(data1[mark1][0])
        time.sleep(3)
        self.dl.input_pwd(data1[mark1][1])
        time.sleep(3)
        self.dl.click_login()
        time.sleep(3)

        #1、修改处遇等级额度【高】【低】
        self.cyed1.click_zfxfgk()
        time.sleep(2)
        self.cyed1.click_cyed()
        time.sleep(2)
        self.cyed1.switch_cyed()
        time.sleep(2)
        self.cyed1.click_ze1bxz()
        time.sleep(2)
        self.cyed1.click_a1bxz()
        time.sleep(2)
        self.cyed1.click_b1bxz()
        time.sleep(2)
        self.cyed1.click_gwcsbxz()
        time.sleep(2)

        # ------【一级处遇等级{高}】A
        self.cyed1.click_a1xz()
        time.sleep(2)
        self.cyed1.input_a1(data2[mark1][6])
        time.sleep(2)
        # ------【二级处遇等级{高}】A
        self.cyed1.click_a2xz()
        time.sleep(2)
        self.cyed1.input_a2(data2[mark1][8])
        time.sleep(2)

        self.cyed1.click_cyedbc()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #2、创建罪犯关联【高】处遇
        self.cyed1.click_jcxxgl()
        time.sleep(2)
        self.cyed1.click_zfxxgl()
        time.sleep(2)
        self.cyed1.switch_zftj()
        time.sleep(2)
        self.cyed1.click_zftj()
        time.sleep(2)
        self.cyed1.click_ssjq()
        time.sleep(2)
        self.cyed1.input_ssjq(data2[mark1][19])
        time.sleep(2)
        self.cyed1.input_zfxm(data2[mark1][1])
        time.sleep(2)
        self.cyed1.input_zfbh(data2[mark1][2])
        time.sleep(2)
        self.cyed1.click_zfxb()
        time.sleep(2)
        self.cyed1.input_zfxbsr(data2[mark1][3])
        time.sleep(2)
        self.cyed1.click_cydj()
        time.sleep(2)
        self.cyed1.input_cydj(data2[mark1][5])
        time.sleep(2)
        self.cyed1.click_srlb()
        time.sleep(2)
        self.cyed1.input_srlb(data2[mark1][4])
        time.sleep(2)
        self.cyed1.click_zflx()
        time.sleep(2)
        self.cyed1.click_bcnr()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #3、罪犯资金上账A
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_xzsz()
        time.sleep(2)
        self.cyed1.switch_outframe()
        time.sleep(2)
        self.cyed1.click_zjszgb()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_szzjfl()
        time.sleep(2)
        self.cyed1.input_szzjfl(data2[mark1][9])
        time.sleep(2)
        self.cyed1.click_szzjlx()
        time.sleep(2)
        self.cyed1.input_szzjlx(data2[mark1][10])
        time.sleep(2)
        self.cyed1.input_szzfxm(data2[mark1][2])
        time.sleep(2)
        self.cyed1.input_szje(data2[mark1][11])
        time.sleep(2)
        self.cyed1.click_qbsz()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szgb()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_tjsz()
        time.sleep(2)
        self.cyed1.click_qrsz()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #4、修改商品在售价格A
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 一关
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_zsspgl()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(4)
        self.cyed1.click_spyjtj()
        time.sleep(3)
        self.cyed1.switch_outframe()
        time.sleep(3)
        self.cyed1.click_zsspgb()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(3)
        self.cyed1.click_xzsp()
        time.sleep(3)
        # 商品1
        self.cyed1.input_spbhsrk(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)
        # 商品2
        self.cyed1.input_spbhsrk(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)

        self.cyed1.click_gbspxz()
        time.sleep(3)
        # 商品一新临售
        self.cyed1.input_sp1xls(data2[mark1][14])
        time.sleep(3)
        # 商品二新临售
        self.cyed1.input_sp2xls(data2[mark1][17])
        time.sleep(3)
        self.cyed1.click_tjtj()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 二开
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #5、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #6、罪犯转处遇等级【低】
        self.zfuser.click_jcxxgl()
        time.sleep(3)
        self.zfuser.click_zfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.input_zfxxcxbhsrk(data2[mark1][2])
        time.sleep(3)
        self.zfuser.click_zfxxglcxan()
        time.sleep(3)
        self.zfuser.click_zfxxglgx()
        time.sleep(3)
        self.zfuser.plzcydj()
        time.sleep(2)
        self.zfuser.switch_outframe()
        time.sleep(3)
        self.zfuser.click_gbzfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.select_xzcydj('128') #低处遇等级
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.driver.refresh()

        #7、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        self.cyed1.switch_outframe()
        self.b = self.zfuser.gett_ddcjsbtknr()
        try:
            self.assertIn('订单创建失败', self.b)
        except:
            self.cyed1.get_img(ut.IMG_PATH + '/罪犯转处遇等级模块_%d.png' % (mark1))
            raise Exception

    def testcase04(self):
        '''用例4，低额等级-》高额等级，【未超额】历史有计入管控消费=》转级后新管控>历史记录管控，新可用=新管控-历史记录管控【可购物】'''
        self.dl.input_name(data1[mark1][0])
        time.sleep(3)
        self.dl.input_pwd(data1[mark1][1])
        time.sleep(3)
        self.dl.click_login()
        time.sleep(3)

        #1、修改处遇等级额度【高】【低】
        self.cyed1.click_zfxfgk()
        time.sleep(2)
        self.cyed1.click_cyed()
        time.sleep(2)
        self.cyed1.switch_cyed()
        time.sleep(2)
        self.cyed1.click_ze1bxz()
        time.sleep(2)
        self.cyed1.click_a1bxz()
        time.sleep(2)
        self.cyed1.click_b1bxz()
        time.sleep(2)
        self.cyed1.click_gwcsbxz()
        time.sleep(2)

        # ------【一级处遇等级{高}】A
        self.cyed1.click_a1xz()
        time.sleep(2)
        self.cyed1.input_a1(data2[mark1][6])
        time.sleep(2)
        # ------【二级处遇等级{高}】A
        self.cyed1.click_a2xz()
        time.sleep(2)
        self.cyed1.input_a2(data2[mark1][8])
        time.sleep(2)

        self.cyed1.click_cyedbc()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #2、创建罪犯关联【低】处遇
        self.cyed1.click_jcxxgl()
        time.sleep(2)
        self.cyed1.click_zfxxgl()
        time.sleep(2)
        self.cyed1.switch_zftj()
        time.sleep(2)
        self.cyed1.click_zftj()
        time.sleep(2)
        self.cyed1.click_ssjq()
        time.sleep(2)
        self.cyed1.input_ssjq(data2[mark1][19])
        time.sleep(2)
        self.cyed1.input_zfxm(data2[mark1][1])
        time.sleep(2)
        self.cyed1.input_zfbh(data2[mark1][2])
        time.sleep(2)
        self.cyed1.click_zfxb()
        time.sleep(2)
        self.cyed1.input_zfxbsr(data2[mark1][3])
        time.sleep(2)
        self.cyed1.click_cydj()
        time.sleep(2)
        self.cyed1.input_cydj(data2[mark1][7])
        time.sleep(2)
        self.cyed1.click_srlb()
        time.sleep(2)
        self.cyed1.input_srlb(data2[mark1][4])
        time.sleep(2)
        self.cyed1.click_zflx()
        time.sleep(2)
        self.cyed1.click_bcnr()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #3、罪犯资金上账A
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_xzsz()
        time.sleep(2)
        self.cyed1.switch_outframe()
        time.sleep(2)
        self.cyed1.click_zjszgb()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_szzjfl()
        time.sleep(2)
        self.cyed1.input_szzjfl(data2[mark1][9])
        time.sleep(2)
        self.cyed1.click_szzjlx()
        time.sleep(2)
        self.cyed1.input_szzjlx(data2[mark1][10])
        time.sleep(2)
        self.cyed1.input_szzfxm(data2[mark1][2])
        time.sleep(2)
        self.cyed1.input_szje(data2[mark1][11])
        time.sleep(2)
        self.cyed1.click_qbsz()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szgb()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_tjsz()
        time.sleep(2)
        self.cyed1.click_qrsz()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #4、修改商品在售价格A
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 一关
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_zsspgl()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(4)
        self.cyed1.click_spyjtj()
        time.sleep(3)
        self.cyed1.switch_outframe()
        time.sleep(3)
        self.cyed1.click_zsspgb()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(3)
        self.cyed1.click_xzsp()
        time.sleep(3)
        # 商品1
        self.cyed1.input_spbhsrk(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)
        # 商品2
        self.cyed1.input_spbhsrk(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)

        self.cyed1.click_gbspxz()
        time.sleep(3)
        # 商品一新临售
        self.cyed1.input_sp1xls(data2[mark1][14])
        time.sleep(3)
        # 商品二新临售
        self.cyed1.input_sp2xls(data2[mark1][17])
        time.sleep(3)
        self.cyed1.click_tjtj()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 二开
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #5、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #6、罪犯转处遇等级【高】
        self.zfuser.click_jcxxgl()
        time.sleep(3)
        self.zfuser.click_zfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.input_zfxxcxbhsrk(data2[mark1][2])
        time.sleep(3)
        self.zfuser.click_zfxxglcxan()
        time.sleep(3)
        self.zfuser.click_zfxxglgx()
        time.sleep(3)
        self.zfuser.plzcydj()
        time.sleep(2)
        self.zfuser.switch_outframe()
        time.sleep(3)
        self.zfuser.click_gbzfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.select_xzcydj('128')  # 高处遇等级
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.driver.refresh()

        #7、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        self.cyed1.switch_outframe()
        self.b = self.zfuser.gett_ddcjsbtknr()
        try:
            self.assertIn('订单创建失败', self.b)
        except:
            self.cyed1.get_img(ut.IMG_PATH + '/罪犯转处遇等级模块_%d.png' % (mark1))
            raise Exception

    def testcase05(self):
        '''用例5，低额等级-》高额等级，【未超额】历史有计入管控消费=》转级后新管控>历史记录管控，新可用=新管控-历史记录管控【可购物】'''
        self.dl.input_name(data1[mark1][0])
        time.sleep(3)
        self.dl.input_pwd(data1[mark1][1])
        time.sleep(3)
        self.dl.click_login()
        time.sleep(3)

        #1、修改处遇等级额度【高】【低】
        self.cyed1.click_zfxfgk()
        time.sleep(2)
        self.cyed1.click_cyed()
        time.sleep(2)
        self.cyed1.switch_cyed()
        time.sleep(2)
        self.cyed1.click_ze1bxz()
        time.sleep(2)
        self.cyed1.click_a1bxz()
        time.sleep(2)
        self.cyed1.click_b1bxz()
        time.sleep(2)
        self.cyed1.click_gwcsbxz()
        time.sleep(2)

        # ------【一级处遇等级{高}】A
        self.cyed1.click_a1xz()
        time.sleep(2)
        self.cyed1.input_a1(data2[mark1][6])
        time.sleep(2)
        # ------【二级处遇等级{高}】A
        self.cyed1.click_a2xz()
        time.sleep(2)
        self.cyed1.input_a2(data2[mark1][8])
        time.sleep(2)

        self.cyed1.click_cyedbc()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #2、创建罪犯关联【低】处遇
        self.cyed1.click_jcxxgl()
        time.sleep(2)
        self.cyed1.click_zfxxgl()
        time.sleep(2)
        self.cyed1.switch_zftj()
        time.sleep(2)
        self.cyed1.click_zftj()
        time.sleep(2)
        self.cyed1.click_ssjq()
        time.sleep(2)
        self.cyed1.input_ssjq(data2[mark1][19])
        time.sleep(2)
        self.cyed1.input_zfxm(data2[mark1][1])
        time.sleep(2)
        self.cyed1.input_zfbh(data2[mark1][2])
        time.sleep(2)
        self.cyed1.click_zfxb()
        time.sleep(2)
        self.cyed1.input_zfxbsr(data2[mark1][3])
        time.sleep(2)
        self.cyed1.click_cydj()
        time.sleep(2)
        self.cyed1.input_cydj(data2[mark1][7])
        time.sleep(2)
        self.cyed1.click_srlb()
        time.sleep(2)
        self.cyed1.input_srlb(data2[mark1][4])
        time.sleep(2)
        self.cyed1.click_zflx()
        time.sleep(2)
        self.cyed1.click_bcnr()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #3、罪犯资金上账A
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_xzsz()
        time.sleep(2)
        self.cyed1.switch_outframe()
        time.sleep(2)
        self.cyed1.click_zjszgb()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_szzjfl()
        time.sleep(2)
        self.cyed1.input_szzjfl(data2[mark1][9])
        time.sleep(2)
        self.cyed1.click_szzjlx()
        time.sleep(2)
        self.cyed1.input_szzjlx(data2[mark1][10])
        time.sleep(2)
        self.cyed1.input_szzfxm(data2[mark1][2])
        time.sleep(2)
        self.cyed1.input_szje(data2[mark1][11])
        time.sleep(2)
        self.cyed1.click_qbsz()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szxyb()
        time.sleep(2)
        self.cyed1.click_szgb()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)
        self.cyed1.click_zjywgl()
        time.sleep(2)
        self.cyed1.click_zjsz()
        time.sleep(2)
        self.cyed1.switch_zjsz()
        time.sleep(2)
        self.cyed1.click_tjsz()
        time.sleep(2)
        self.cyed1.click_qrsz()
        time.sleep(2)
        self.driver.refresh()
        time.sleep(2)

        #4、修改商品在售价格A
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 一关
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_zsspgl()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(4)
        self.cyed1.click_spyjtj()
        time.sleep(3)
        self.cyed1.switch_outframe()
        time.sleep(3)
        self.cyed1.click_zsspgb()
        time.sleep(3)
        self.cyed1.switch_zsspgl()
        time.sleep(3)
        self.cyed1.click_xzsp()
        time.sleep(3)
        # 商品1
        self.cyed1.input_spbhsrk(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)
        # 商品2
        self.cyed1.input_spbhsrk(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_cpcx()
        time.sleep(3)
        self.cyed1.click_xzspgx()
        time.sleep(3)

        self.cyed1.click_gbspxz()
        time.sleep(3)
        # 商品一新临售
        self.cyed1.input_sp1xls(data2[mark1][14])
        time.sleep(3)
        # 商品二新临售
        self.cyed1.input_sp2xls(data2[mark1][17])
        time.sleep(3)
        self.cyed1.click_tjtj()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)
        self.cyed1.click_jcxxgl()
        time.sleep(3)
        self.cyed1.click_ckxxgl()
        time.sleep(3)
        self.cyed1.switch_ckxxgl()
        time.sleep(3)
        self.cyed1.click_ck1zcck()  # 二开
        time.sleep(3)
        self.cyed1.click_cktkqr()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #5、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][13])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        time.sleep(3)
        self.driver.refresh()
        time.sleep(3)

        #6、罪犯转处遇等级【高】
        self.zfuser.click_jcxxgl()
        time.sleep(3)
        self.zfuser.click_zfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.input_zfxxcxbhsrk(data2[mark1][2])
        time.sleep(3)
        self.zfuser.click_zfxxglcxan()
        time.sleep(3)
        self.zfuser.click_zfxxglgx()
        time.sleep(3)
        self.zfuser.plzcydj()
        time.sleep(2)
        self.zfuser.switch_outframe()
        time.sleep(3)
        self.zfuser.click_gbzfxxgl()
        time.sleep(3)
        self.zfuser.switch_zftj()
        time.sleep(3)
        self.zfuser.select_xzcydj('128')  # 高处遇等级
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.zfuser.click_zcydjxyb()
        time.sleep(2)
        self.driver.refresh()

        #7、供应站销售成功
        self.cyed1.click_xsywgl()
        time.sleep(3)
        self.cyed1.click_gyzxs()
        time.sleep(3)
        self.cyed1.switch_gyzxs()
        time.sleep(3)
        self.cyed1.input_gyzzfxm(data2[mark1][2])
        time.sleep(3)
        self.cyed1.click_cksrk()
        time.sleep(3)
        self.cyed1.input_cksrk(data2[mark1][18])
        time.sleep(3)
        self.cyed1.input_spbh(data2[mark1][16])
        time.sleep(3)
        self.cyed1.click_spxsjz()
        time.sleep(3)
        self.cyed1.click_qrjz()
        self.cyed1.switch_outframe()
        self.b = self.zfuser.gett_ddcjsbtknr()
        try:
            self.assertIn('订单创建失败', self.b)
        except:
            self.cyed1.get_img(ut.IMG_PATH + '/罪犯转处遇等级模块_%d.png' % (mark1))
            raise Exception


if __name__=='__main__':
    unittest.main()